#!/bin/bash
# Setting up pacman.conf
nano /etc/pacman.conf

# Setting up timezone
ln -sf /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
hwclock --systohc

# Setting up locale
echo sv_SE.UTF-8 UTF-8 >> /etc/locale.gen
echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
locale-gen
echo LANG=sv_SE.UTF-8 >> /etc/locale.conf
echo KEYMAP=sv-latin1 >> /etc/vconsole.conf

# Setting up /etc/hostname
echo arch-laptop >> /etc/hostname
echo 127.0.0.1	localhost >> /etc/hosts
echo ::1		    localhost >> /etc/hosts
echo 127.0.1.1  arch-laptop >> /etc/hosts

#Running reflector and updating mirrorlist
reflector -f 25 -l 25 -n 25 > /etc/pacman.d/mirrorlist

# Starting installation
pacman -Syy
pacman-key --populate archlinux
passwd

# KDE with minimal applications
pacman -S --noconfirm grub efibootmgr xorg xorg-server sddm plasma networkmanager kcalc konsole kate gwenview dolphin kpmcore xdg-user-dirs sudo ark p7zip unrar unarchiver lzop lrzip partitionmanager fuse libreoffice-fresh-sv firefox gparted lutris wine wine-gecko wine-mono winetricks vlc qbittorrent htop neofetch nvidia nvidia-utils nvidia-settings steam os-prober opencl-nvidia fish git

# Preparing boot partition and installing grub
mkdir /boot/efi
mount /dev/nvme0n1p1 /boot/efi
grub-install --target=x86_64-efi --bootloader-id=Arch --efi-directory=/boot/efi
grub-mkconfig -o /boot/grub/grub.cfg

# Enabling Services and adding accounts
systemctl enable sddm.service
systemctl enable NetworkManager
useradd -m modda
passwd modda
xdg-user-dirs-update
EDITOR=nano visudo
mv /user /home/modda/user
cd /home/modda
su modda
