#!/bin/bash
# Formatting drives and setting up swap
mkfs.fat -F32 /dev/nvme0n1p1
mkswap /dev/nvme0n1p2
swapon /dev/nvme0n1p2
mkfs.ext4 /dev/nvme0n1p3
mkfs.ext4 /dev/nvme1n1p1

# Mounting root partition and home folder
mount /dev/nvme0n1p3 /mnt
mkdir /mnt/home
mount /dev/nvme1n1p1 /mnt/home

# Setting up pacman.conf
nano /etc/pacman.conf

# Updating pacman
pacman -Syy

# Installing and running reflector
pacman -S --noconfirm reflector
reflector -f 12 -l 12 -n 12 > /etc/pacman.d/mirrorlist

# Downloading base for install
pacstrap /mnt base base-devel linux linux-firmware nano reflector

# Generating /etc/fstab on new system
genfstab -U /mnt >> /mnt/etc/fstab

# Moving configuration files to new system
mv install /mnt
mv user /mnt

# Chroot into new system
arch-chroot /mnt
