#!/bin/bash

# Setting up home directory folders

# Installing git and yay
sudo pacman -S git
cd /opt
sudo git clone https://aur.archlinux.org/yay-git.git
sudo chown -R modda:modda ./yay-git
cd yay-git
makepkg -si

# Updating yay and downloading Spotify
yay -Syy
curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | gpg --import -
yay -S spotify steam-fonts optimus-manager-qt-git #lightdm-webkit-theme-aether-git <- xfce4 only
sudo systemctl enable optimus-manager.service
chsh -s /usr/bin/fish
sudo chsh -s /usr/bin/fish
